### ISSUE TITLE
Share receiver not working.

### ISSUE THREAD

**Issue by stefanmaric** [telegram-s/telegram#12]
I'm using Telegram S 1.3.1010 on Android 4.4.2.

When using Android's share feature (ACTION_SEND, I believe) from any app Telegram's receiver doesn't work. It does appear on the applications list and opens Telegram to select the conversation, I select the conversation and it does nothing but opens that conversation. This behavior applies to any kind of content.

**Comment by ex3ndr** [comment]
Already fixed this
