### ISSUE TITLE
Call and send SMS actions from Contact Details view.

### ISSUE THREAD

**Issue by stefanmaric** [telegram-s/telegram#20]
The Contact details view shows contact's number and 'message' icon, just like Whatsapp, but unlike Whatsapp they don't trigger Call and Send SMS actions (to be handle by another app). 

This feature is quite useful (so useful that Whatsapp includes the Call action directly from the chat Spinner), it would be cool to have this feature in Telegram. :D

**Comment by ex3ndr** [comment]
This feature is planned in some days/weeks

**Comment by stefanmaric** [comment]
Wow, pretty awesome!

I would implement it myself, but I'm not an Android dev. :(
