### ISSUE TITLE
The scrollbar in "Contacts" does not scale properly

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegram-s/telegram#37]
Some she scrollbar in "Contacts" is larger than the size of the screen. The slider disappears behind the navigation buttons if i I scroll down.

**Comment by ex3ndr** [comment]
Already fixed, but not released.

**Comment by ManuelSchneid3r** [comment]
Do you maintain a private repo? I just built the debug version. The issue persists.

Regards

**Comment by ex3ndr** [comment]
Yes, i have two repos. Private and public. In each release i push private repo to this one.

**Comment by ManuelSchneid3r** [comment]
Could you please consider to publish the current state of the development in a testing branch? It makes it easier for others to contribute. Are you interested in a development community, at all? If not would you mind if I fork your code to build a community based Telegram client?

**Comment by ex3ndr** [comment]
I am mostly work for optimizing for community development, but for now after next release i'll started with testing branch.

BTW sometimes we need to hide some development process, because we doesn't want to show incomplete things, this may harm our product.
