### ISSUE TITLE
What is the difference to original telegram app

### ISSUE THREAD

**Issue by jonnius** [telegram-s/telegram#49]
Could you point out, what are the differences to the original telegram app?

**Comment by ex3ndr** [comment]
They are developed independently by different developers.

**Comment by jonnius** [comment]
But it looks totally the same. So my question is just, are there any differences in features (or look)?

**Comment by ex3ndr** [comment]
They are not same in design. You may check Telegram S Beta with updated design. Telegram S supports GIF-Animations, customizations of themes.

**Comment by jonnius** [comment]
Nice.
