### ISSUE TITLE
What is the video codec that supports Telegram?

### ISSUE THREAD

**Issue by Abejo** [telegram-s/telegram#50]
Hello, what is the video codec that supports Telegram?
I edited a video with Avidemux (xvid and mp3) and does not allow me to transfer as video

**Comment by alejandro-amo** [comment]
xvid??
not 100% sure but most probably is "normal" mp4

**Comment by ex3ndr** [comment]
mpeg4 baseline profile.

**Comment by hzv4424** [comment]
[https://core.telegram.org/blackberry/chat-media-send](url)

Video dimensions must be set to 480x320 (320x480 for vertical videos).
H.264 and MPEG-4 should be used as the codec and container.

this is the best one:
[http://www.x264pro.com/](url)
