### ISSUE TITLE
Feature request: go to bottom button in chats.

### ISSUE THREAD

**Issue by stefanmaric** [telegram-s/telegram#58]
A button to directly scroll down to the end of the conversation when a new message comes in or when you're scrolling down would be nice. :D

**Comment by Ecron** [comment]
Yes, it would be great 'cause when searching in conversation's history it's a pain in the ass to get back to the very recent messages (you can always get out of the chat and go back in, but, you know, a button would be awesome) :smile:

**Comment by Littleprince18** [comment]
When you click on a group chat that could have hundreds of messages, does the chat feed open at the top or the bottom of the feed please!? I keep reading conflicting information and I'm trying to find out what it currently does for iphone and android aswell as the version behaviour at the end of 2018/beginning if 2019 please

**Comment by Ecron** [comment]
This project was discontinued 5 years ago. The last code of the official app can be found here: https://github.com/DrKLO/Telegram
